version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: backend
    restart: always
    env_file:
      - ./envs/dev.env
    command: "tail -f /dev/null"
    ports:
      - '8000:8000'
      - '4777:22'
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files

  services:
    email:
      image: "your_image"
      restart: always
      env_file:
        - ./database.env
      command: 'python manage.py send_mail'
      volumes:
        - ./backend:/backend
        - ./media-files:/media-files
        - ./static-files:/static-files
      depends_on:
        - postgres
        - backend



  # for nginx and gunicorn see docker-compose.deploy.yml


volumes:
  postgres:
  media-files:
  static-files:


