# Generated by Django 3.0.3 on 2020-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200312_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of likes'),
        ),
    ]
